16 get product by
GSG-G9/MASA-Store pull request #45
Opened 2021-02-03 14:09 UTC by AlaaShurrab

fixes #16 
- creating a database query to fetch the data of one product using the params as shown in the issue 
- adding the route and connecting the route to the API 
- testing for the database query and for the route

2021-02-03 15:32 UTC, Sondos-Alalami submitted a review, later dismissed

2021-02-03 17:35 UTC, Sondos-Alalami approved these changes, later dismissed

2021-02-03 19:02 UTC, mFlaifel requested changes

2021-02-03 19:02 UTC, mFlaifel commented on __test__/getProductById.test.js
> +const app = require('../server/app');
please add an empty line here to separate your modules from the third-party modules

2021-02-03 19:02 UTC, mFlaifel commented on __test__/getProductById.test.js
> +describe('Test Routes, Test Database getAllProducts query', () => {
please change the description 
```suggestion
describe(`Test '/product/:productId' route, and test  get product by id  query`, () => {
```

2021-02-03 19:02 UTC, mFlaifel commented on server/controllers/common/productByIdHandler.js
> +};
if the product id doesn't exist, send a message like ' product does not exist'
```
res.json({
status:404,
message: 'product does not exist',
data: [ ]
})
```

2021-02-03 19:02 UTC, mFlaifel commented on server/database/queries/index.js
>  const getOrders = require('./getOrders');
please arrange all related routes by their category
```suggestion
const getAllProducts = require('./getAllProducts');
const getProductById = require('./getProductById');
const getClients = require('./getClients');
const getOrders = require('./getOrders');
```

2021-02-03 19:02 UTC, mFlaifel commented on server/database/queries/index.js
> +  getProductById,
```suggestion
  getAllProducts,
  getProductById,
  getClients,
  getOrders,
```

2021-02-04 08:42 UTC, AlaaShurrab commented on __test__/getProductById.test.js
> +const app = require('../server/app');
done

2021-02-04 08:43 UTC, AlaaShurrab commented on __test__/getProductById.test.js
> +describe('Test Routes, Test Database getAllProducts query', () => {
done

2021-02-04 08:59 UTC, AlaaShurrab commented on server/controllers/common/productByIdHandler.js
> +};
done, also added a test to check this case out

2021-02-04 11:02 UTC, mFlaifel approved these changes

2021-02-04 15:41 UTC, merged