GET products/:Category
GSG-G9/MASA-Store pull request #51
Opened 2021-02-04 14:41 UTC by AlaaShurrab

fixes #26 
creating the query to get the data with a category and connecting the route to the API, also making tests to check the data

Relates #26

2021-02-04 17:56 UTC, mFlaifel requested changes

2021-02-04 17:56 UTC, mFlaifel commented on __test__/getProductsByCatogory.test.js
> +      // console.log(JSON.parse(res.text), '**************************');
please, remove the comment code

2021-02-04 20:43 UTC, Sondos-Alalami submitted a review, later dismissed

2021-02-05 01:15 UTC, mFlaifel approved these changes

2021-02-05 01:16 UTC, mFlaifel requested changes

2021-02-05 01:16 UTC, mFlaifel commented on server/routes/common.js
> +commonRouter.get('/products', allProductsHandler);
please, remove this line

2021-02-06 17:34 UTC, merged