creating the log out route
GSG-G9/MASA-Store pull request #64
Opened 2021-02-07 18:15 UTC by AlaaShurrab

fixes #17 
creating logOut route to delete the tokens

2021-02-07 19:23 UTC, Ahmed-aed submitted a review, later dismissed

2021-02-08 07:31 UTC, mFlaifel requested changes

2021-02-08 07:31 UTC, mFlaifel commented on server/controllers/common/signoutHandler.js
> +};
the try-catch doesn't work here, 
you can check cookies from the request, if they exist you can clear them, if not you send a message like 'you'r not log in'

2021-02-08 07:31 UTC, mFlaifel commented on server/routes/common.js
>  commonRouter.post('/signup', signUpHandler);
why you use the "PUT" method, I think the post is more appropriate.

[link](https://stackoverflow.com/questions/3521290/logout-get-or-post)

2021-02-08 19:55 UTC, Sondos-Alalami approved these changes

2021-02-08 21:53 UTC, Ahmed-aed approved these changes
Great job

2021-02-09 07:34 UTC, mFlaifel approved these changes

2021-02-09 07:35 UTC, merged