FRONT-END ESling Config
GSG-G9/MASA-Store pull request #98
Opened 2021-02-09 10:02 UTC by AlaaShurrab

fixes #71
creating .eslintrc file 
and adding some rules

2021-02-09 11:16 UTC, mFlaifel commented on client/.eslintrc
> +    "plugin:jsx-a11y/recommended",
jsx-a11y is installed by default in create-react-app so delete it

2021-02-09 11:17 UTC, mFlaifel commented on client/.eslintrc
> +      }
please test these rules in your code editor.

2021-02-09 11:17 UTC, mFlaifel requested changes
need some improvemnt

2021-02-09 13:23 UTC, Sondos-Alalami submitted a review, later dismissed

2021-02-09 18:00 UTC, mFlaifel approved these changes, later dismissed

2021-02-10 13:54 UTC, mFlaifel approved these changes

2021-02-10 13:54 UTC, merged